config/routes.rb
Rails.application.routes.draw do
  resources :organizations do
    resources :events
  end
  get 'events' => 'events#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  default_scope { order(timestamp: :desc) } #used to sort by default
  scope :by_organization_id, -> (organization_id) {
    where(organization_id: organization_id)
  }
  scope :by_hostname, -> (hostname) { where(hostname: hostname) }
  belongs_to :organization

  validates :organization_id, presence: true
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  default_scope { order(created_at: :desc) }
  has_many :events, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  def set_organization
    return if params[:organization_id].nil?
    @organization = Organization.find_by_name(params[:organization_id])
    if (@organization == nil)
      @organization = Organization.find(params[:organization_id])
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_organization
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event
    @events = filtered_by_organization(@events)
    @events = filtered_by_result_count(@events)
    @events = filtered_by_hostname(@events)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.organization_id = @organization.id
    respond_to do |format|
      if @event.save
        format.html { redirect_to organization_event_path(@organization, @event), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: organization_event_path(@organization, @event) }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to organization_event_path(@organization, @event), notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to organization_events_url(@organization), notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def filtered_by_organization(events)
    if @organization
      events.by_organization_id(@organization.id)
    else
      events
    end
  end

  def filtered_by_result_count(events)
    if safe_params.keys.include? "count"
      events.limit(safe_params["count"])
    else
      events.all
    end
  end

  def filtered_by_hostname(events)
    if safe_params.keys.include? "hostname"
      events.by_hostname(safe_params["hostname"])
    else
      events
    end
  end

  def set_event
    @event = Event.find(params[:id])
  end

  #filter params
  def safe_params
    params.permit(:organization_id, :count, :hostname)
  end

  #params for building up an event
  def event_params
    params.require(:event).permit(:message, :hostname, :timestamp)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_organization
    @organization = Organization.find_by_name(params[:id])
    @organization = Organization.find(params[:id]) if @organization.nil?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def organization_params
    params.require(:organization).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event, url: organization_events_path(@organization)) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= organization_events_path(@organization) %>
  sfkgjsdl;fjg
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :hostname %><br>
    <%= f.text_field :hostname %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br>
    <%= f.datetime_select :timestamp %>
  </div>
  <div class="field">
    <%= f.label :organization_id %><br>
    <%= f.number_field :organization_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', organization_event_path(@organization, @event) %> |
<%= link_to 'Back', organization_events_path(@organization) %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>Hostname</th>
      <th>Timestamp</th>
      <th>Organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.message %></td>
        <td><%= event.hostname %></td>
        <td><%= event.timestamp %></td>
        <td><%= event.organization_id %></td>
        <td><%= link_to 'Show', organization_event_path(event.organization_id, event) %></td>
        <td><%= link_to 'Edit', edit_organization_event_path(event.organization_id, event) %></td>
        <td><%= link_to 'Destroy', organization_event_path(event.organization_id, event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%=  link_to 'New Event', new_organization_event_path(@organization) if @organization %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', organization_events_path(@organization) %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @event.message %>
</p>

<p>
  <strong>Hostname:</strong>
  <%= @event.hostname %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @event.timestamp %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @event.organization_id %>
</p>

<%= link_to 'Edit', edit_organization_event_path(@organization, @event) %> |
<%= link_to 'Back', organization_events_path(@organization) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Evently</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>